### ISSUE TITLE
duplicate tooltips in opened left menu

### ISSUE THREAD

**Issue by githubertus** [lianglee/Flexi#5]
I'm getting a first tooltip when hovering `<li class='menu-section-item-....'` 
and another one on `<a class='menu-section-item-a-....'`

![flexi-duplicate-tooltips](https://user-images.githubusercontent.com/9904364/52900415-bf6f4600-31f5-11e9-952e-7efb4e059dea.PNG)

Question is: Do we need any tooltips at all if the menu is expanded? To my opinion: No.

**Comment by lianglee** [comment]
Fixed, i tried to not to show any tool tip but its bit tricky for me to do that (maybe i need to re-think with fresh mind) but i just modified to show only one tool-tip
