### ISSUE TITLE
very limited usability on screen widths from 767px - 1141px

### ISSUE THREAD

**Issue by githubertus** [lianglee/Flexi#7]
1. search input fields and top menu items appear below topbar
2. left menu starts in wide mode and can't be shrinked
![flexi-screen-range](https://user-images.githubusercontent.com/9904364/53010391-18c9b600-343e-11e9-91d2-eecd7d91993f.png)

**Comment by Acutler1** [comment]
Having this same problem.

**Comment by lianglee** [comment]
Solved,  you may try a new patch : https://github.com/lianglee/Flexi/archive/master.zip
