### ISSUE TITLE
Bug Report: Components overlapping

### ISSUE THREAD

**Issue by Acutler1** [lianglee/Flexi#8]
On both the demo site on Softlab & when I installed it on my site to test it, the sidebar component overlapped the main newsfeed. 
<img width="1280" alt="Screen Shot 2019-05-13 at 2 19 59 PM" src="https://user-images.githubusercontent.com/50600715/57659162-52c6d600-75af-11e9-8427-d4f19b13c478.png">

**Comment by lianglee** [comment]
Please provide the width of your screen

**Comment by lianglee** [comment]
Solved #7

**Comment by Acutler1** [comment]
@lianglee Unfortunately the issue is still present after trying the patch. The display is a MacBook Pro Retina 13" and the browser is Firefox. 

<img width="1280" alt="Screen Shot 2019-05-22 at 1 52 58 PM" src="https://user-images.githubusercontent.com/50600715/58196796-0f4c2600-7c99-11e9-94dd-be2ac5f21ed1.png">

**Comment by lianglee** [comment]
Will check on it, i reopened it.

Can you please confirm if you removed old theme first,  then uploaded new theme,  then flushed your website cache from admin area?

**Comment by Acutler1** [comment]
Yes, deleted the old theme, flushed the website cache and the browser cache, uploaded the patched theme.

**Comment by lianglee** [comment]
Fixed 1.5
